### ISSUE TITLE
Using plugin break nested pages

### ISSUE THREAD

**Issue by SebKay** [athlan/acf-permalink#12]
Hi,

This plugin works perfectly with the custom fields for posts and custom post types, however, there's what seems to be a bug where nested pages go to a 404 when this plugin is active.

Any ideas why this might be?

**Comment by athlan** [comment]
Hello @SebKay .

Please ensure that you are using https://github.com/athlan/wordpress-custom-fields-permalink-plugin plugin at version 1.5.0. It should be working fine after fix https://github.com/athlan/wordpress-custom-fields-permalink-plugin/issues/38.

Cheers.

**Comment by SebKay** [comment]
Hi @athlan,

I've made sure to update to the latest version but unfortunately, the nested pages are still going to a 404.

**Comment by athlan** [comment]
Hello,

1. Please provide permalink structure you have, I"ll try to recreate issue in tests.
2. Also please check if plugin works well for not nested pages for you.
3. For nested pages make sure that custom fields are filled.

**Comment by SebKay** [comment]
1. The permalink structure I have is: /%field_ph_post_format%/%postname%/.
1. The plugin works fine for non-nested page.
1. The issue is the custom fields don't exist on the pages that are going to a 404. This seems like it should work though, as not every single post and page is going to have the same custom fields attached.

**Comment by athlan** [comment]
Hello @SebKay . Thank you for providing details within short time.
The problem is in wordpress-custom-fields-permalink plugin.

Let me open the corresponding issue:
https://github.com/athlan/wordpress-custom-fields-permalink-plugin/issues/41

Picking this up.
