### ISSUE TITLE
Stripping characters from the AFC field

### ISSUE THREAD

**Issue by shimsim** [athlan/acf-permalink#14]
When I used this plugin together with ACF to append some text to the end of the permalink, it is adding the text but its stripping out things like ? or = from the text, so I cant get the correct URL. Is this a limitation or bug in the plugin or am I doing something wrong ?

example of the text I am trying to append to the permalink 

?_news_product=d2

I end up with _news_productd2

**Comment by athlan** [comment]
Hello. I am wondering whether it's possible without plugin in core permalink structure, thus it won't take an effect with plugin (either in permalink structure or values like post title).

In general all strings beeing used in url (post meta values) are filtered using url-friendly function stripping chars like you mentioned.

**Comment by shimsim** [comment]
Hi Athlan,
So is there any workaround for this? 
I am not an experienced programmer, is there anything I can try?

**Comment by athlan** [comment]
Hello. All values processed by plugin are wrapped by [`sanitize_title`](https://codex.wordpress.org/Function_Reference/sanitize_title), hence for now it's not possible. I do not see any particular real-live example how it could be used comparing it to how in general permalink mechanism works in WordPress platform.
