### ISSUE TITLE
Using Options Page

### ISSUE THREAD

**Issue by shaneha12** [athlan/acf-permalink#15]
Is there any way it can pull data for generating the URL from the ACF options page instead of individual posts / pages?

**Comment by athlan** [comment]
Hello @shaneha12 . For now it's designed to use post's data.

Could you give some example of such use case? What kind of option?

Because plugin is extensible and some static values could be used or some logic can be programmed. Link to wikipage:
* https://github.com/athlan/wordpress-custom-fields-permalink-plugin/wiki/FAQ

**Comment by shaneha12** [comment]
Thanks for replying. I suppose an example would be in the option page that you can setup with ACF, would be having a field for a city which you can then apply dynamically to a url.

**Comment by shaneha12** [comment]
Where ACF permalinks pulls the $field_name data for the permalink, how would the 'option' field get pulled in the same time.

For example, normally you would use get_field('field_name', 'option'); to pull from the option page. How would i apply that same method to ACF permalinks?

On the permalinks page, %field_service_area% is specified to pull the field generically from each post page so maybe an option of %field_service_area-option% instead to pull from the option page?

**Comment by athlan** [comment]
What `get_field('field_name', 'option')` stands for sorry? https://www.advancedcustomfields.com/resources/get_field/
Its general site option? If so, why not just hardcode it in url?

For now plugin is post-oriented and I really don't see any benefit of using it for options page.
It of course can be extended for specific usecase (https://github.com/athlan/wordpress-custom-fields-permalink-plugin/wiki/FAQ) I don't feel its general usecase for users.

**Comment by shaneha12** [comment]
Yeah its for the options page to pull from. I sorted it out and got it working by hardcoding it like you said. Appreciate the help. Works a treat.
